import{g as n,S as i}from"../ScrollTrigger.js";n.registerPlugin(i);document.addEventListener("DOMContentLoaded",function(){m(),y(),g()});function m(){const e=document.querySelector(".contact-form form");if(!e)return;e.addEventListener("submit",function(o){o.preventDefault();const a=new FormData(e),r=Object.fromEntries(a),p=["name","email","message"];let l=!0;p.forEach(d=>{const u=e.querySelector(`[name="${d}"]`);!r[d]||r[d].trim()===""?(c(u,"This field is required"),l=!1):s(u)});const S=e.querySelector('[name="email"]');r.email&&!f(r.email)&&(c(S,"Please enter a valid email address"),l=!1),l&&v()}),e.querySelectorAll("input, textarea, select").forEach(o=>{o.addEventListener("blur",function(){h(o)}),o.addEventListener("input",function(){s(o)})})}function h(e){const t=e.value.trim(),o=e.name;return e.hasAttribute("required")&&!t?(c(e,"This field is required"),!1):o==="email"&&t&&!f(t)?(c(e,"Please enter a valid email address"),!1):(s(e),!0)}function c(e,t){s(e),e.classList.add("error");const o=document.createElement("div");o.className="field-error",o.textContent=t,e.parentNode.appendChild(o),n.fromTo(o,{opacity:0,y:-10},{opacity:1,y:0,duration:.3})}function s(e){e.classList.remove("error");const t=e.parentNode.querySelector(".field-error");t&&t.remove()}function f(e){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}function v(e){const t=document.querySelector('.contact-form button[type="submit"]'),o=t.textContent;t.textContent="Sending...",t.disabled=!0,setTimeout(()=>{E(),document.querySelector(".contact-form form").reset(),t.textContent=o,t.disabled=!1},2e3)}function E(){const e=document.querySelector(".contact-form"),t=document.createElement("div");t.className="success-message",t.innerHTML=`
    <div class="success-content">
      <i class="fas fa-check-circle"></i>
      <h3>Message Sent Successfully!</h3>
      <p>Thank you for contacting us. We'll get back to you soon.</p>
    </div>
  `,e.appendChild(t),n.fromTo(t,{opacity:0,scale:.8},{opacity:1,scale:1,duration:.5,ease:"back.out(1.7)"}),setTimeout(()=>{n.to(t,{opacity:0,scale:.8,duration:.3,onComplete:()=>t.remove()})},5e3)}function y(){const e=document.querySelector(".hero .container");if(e){const a=e.querySelector("h1"),r=e.querySelector("p");n.set([a,r],{opacity:0,y:30}),n.to([a,r],{opacity:1,y:0,duration:.8,stagger:.2,ease:"power2.out",delay:.3})}const t=document.querySelector(".contact-form");t&&(n.set(t,{opacity:0,x:-50}),i.create({trigger:t,start:"top 80%",onEnter:()=>{n.to(t,{opacity:1,x:0,duration:.8,ease:"power2.out"})}}));const o=document.querySelectorAll(".info-card");o.length>0&&(n.set(o,{opacity:0,y:40}),i.create({trigger:".contact-info",start:"top 80%",onEnter:()=>{n.to(o,{opacity:1,y:0,duration:.6,stagger:.2,ease:"power2.out"})}}))}function g(){const e=document.querySelector(".map-container");e&&(e.innerHTML=`
    <div style="width: 100%; height: 100%; background: #f0f0f0; display: flex; align-items: center; justify-content: center; color: #666;">
      <div style="text-align: center;">
        <i class="fas fa-map-marker-alt" style="font-size: 3rem; margin-bottom: 1rem;"></i>
        <p>Interactive Map Coming Soon</p>
        <p style="font-size: 0.9rem;">123 Beauty Street, London, SW1A 1AA</p>
      </div>
    </div>
  `)}window.addEventListener("beforeunload",function(){i.getAll().forEach(e=>e.kill())});window.LeadingEdge=window.LeadingEdge||{};window.LeadingEdge.contact={initContactForm:m,initScrollAnimations:y,initMap:g};
