color: null
fieldLayouts:
  101f2b79-8b4f-428b-a129-7bf9836aa736:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-29T10:14:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 17aea915-8257-4a12-8811-5fc884aa768c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f076019d-5071-48c8-912c-7c30b9ac3e81
        userCondition: null
handle: contactUs
hasTitleField: true
icon: phone
name: 'Contact Us'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
