defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 443199cf-ce0e-45ec-9c56-c9dd0895e0aa # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  778898bd-c954-4159-a117-36edc766a017: # tle-new
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
