defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3169df3d-45be-43b0-be3b-31683800d693 # Services
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  778898bd-c954-4159-a117-36edc766a017: # tle-new
    enabledByDefault: true
    hasUrls: true
    template: services.twig
    uriFormat: 'our-services/{slug}'
type: channel
