altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6d061cc1-80b0-46a5-ad57-c39df05fdfd9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-30T13:26:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b24fe51e-f62f-4c93-b63d-dbc4fd947dfc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 082e16f9-4b0c-4448-9d6a-095987a9d658
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
